using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Praca_Inżynierska
{
    public class Settings
    {
        public string CPBaudRate { get; set; }
        public string CPDataBits { get; set; }
        public string CPStopBits { get; set; }
        public string CPParity { get; set; }
        public string SlaveAddressM1 { get; set; }
        public string SlaveAddressM2DC { get; set; }
        public string SlaveAddressM2Asynch { get; set; }
        public string SlaveAddressM2BLDC { get; set; }
        public string SlaveAddressM2PMSM { get; set; }
        public string AddrM1SpeedS { get; set; }
        public string AddrM1PositionS { get; set; }
        public string AddrM1TorqueS { get; set; }
        public string AddrM1CurrentS { get; set; }
        public string AddrM1VoltageS { get; set; }
        public string AddrM1PS { get; set; }
        public string AddrM1IS { get; set; }
        public string AddrM1DS { get; set; }
        public string AddrM1x1S { get; set; }
        public string AddrM1x2S { get; set; }
        public string AddrM1x3S { get; set; }
        public bool CheckM1SpeedS { get; set; }
        public bool CheckM1PositionS { get; set; }
        public bool CheckM1TorqueS { get; set; }
        public bool CheckM1CurrentS { get; set; }
        public bool CheckM1VoltageS { get; set; }
        public bool CheckM1PS { get; set; }
        public bool CheckM1IS { get; set; }
        public bool CheckM1DS { get; set; }
        public bool CheckM1x1S { get; set; }
        public bool CheckM1x2S { get; set; }
        public bool CheckM1x3S { get; set; }
        public string AddrM1SpeedR { get; set; }
        public string AddrM1PositionR { get; set; }
        public string AddrM1TorqueR { get; set; }
        public string AddrM1CurrentR { get; set; }
        public string AddrM1VoltageR { get; set; }
        public string AddrM1PR { get; set; }
        public string AddrM1IR { get; set; }
        public string AddrM1DR { get; set; }
        public string AddrM1x1R { get; set; }
        public string AddrM1x2R { get; set; }
        public string AddrM1x3R { get; set; }
        public bool CheckM1SpeedR { get; set; }
        public bool CheckM1PositionR { get; set; }
        public bool CheckM1TorqueR { get; set; }
        public bool CheckM1CurrentR { get; set; }
        public bool CheckM1VoltageR { get; set; }
        public bool CheckM1PR { get; set; }
        public bool CheckM1IR { get; set; }
        public bool CheckM1DR { get; set; }
        public bool CheckM1x1R { get; set; }
        public bool CheckM1x2R { get; set; }
        public bool CheckM1x3R { get; set; }
        public string AddrM2DCSpeedS { get; set; }
        public string AddrM2DCPositionS { get; set; }
        public string AddrM2DCTorqueS { get; set; }
        public string AddrM2DCCurrentS { get; set; }
        public string AddrM2DCVoltageS { get; set; }
        public string AddrM2DCPS { get; set; }
        public string AddrM2DCIS { get; set; }
        public string AddrM2DCDS { get; set; }
        public string AddrM2DCx1S { get; set; }
        public string AddrM2DCx2S { get; set; }
        public string AddrM2DCx3S { get; set; }
        public bool CheckM2DCSpeedS { get; set; }
        public bool CheckM2DCPositionS { get; set; }
        public bool CheckM2DCTorqueS { get; set; }
        public bool CheckM2DCCurrentS { get; set; }
        public bool CheckM2DCVoltageS { get; set; }
        public bool CheckM2DCPS { get; set; }
        public bool CheckM2DCIS { get; set; }
        public bool CheckM2DCDS { get; set; }
        public bool CheckM2DCx1S { get; set; }
        public bool CheckM2DCx2S { get; set; }
        public bool CheckM2DCx3S { get; set; }
        public string AddrM2DCSpeedR { get; set; }
        public string AddrM2DCPositionR { get; set; }
        public string AddrM2DCTorqueR { get; set; }
        public string AddrM2DCCurrentR { get; set; }
        public string AddrM2DCVoltageR { get; set; }
        public string AddrM2DCPR { get; set; }
        public string AddrM2DCIR { get; set; }
        public string AddrM2DCDR { get; set; }
        public string AddrM2DCx1R { get; set; }
        public string AddrM2DCx2R { get; set; }
        public string AddrM2DCx3R { get; set; }
        public bool CheckM2DCSpeedR { get; set; }
        public bool CheckM2DCPositionR { get; set; }
        public bool CheckM2DCTorqueR { get; set; }
        public bool CheckM2DCCurrentR { get; set; }
        public bool CheckM2DCVoltageR { get; set; }
        public bool CheckM2DCPR { get; set; }
        public bool CheckM2DCIR { get; set; }
        public bool CheckM2DCDR { get; set; }
        public bool CheckM2DCx1R { get; set; }
        public bool CheckM2DCx2R { get; set; }
        public bool CheckM2DCx3R { get; set; }
        public string AddrM2AsynchSpeedS { get; set; }
        public string AddrM2AsynchPositionS { get; set; }
        public string AddrM2AsynchTorqueS { get; set; }
        public string AddrM2AsynchCurrentS { get; set; }
        public string AddrM2AsynchVoltageS { get; set; }
        public string AddrM2AsynchPS { get; set; }
        public string AddrM2AsynchIS { get; set; }
        public string AddrM2AsynchDS { get; set; }
        public string AddrM2Asynchx1S { get; set; }
        public string AddrM2Asynchx2S { get; set; }
        public string AddrM2Asynchx3S { get; set; }
        public bool CheckM2AsynchSpeedS { get; set; }
        public bool CheckM2AsynchPositionS { get; set; }
        public bool CheckM2AsynchTorqueS { get; set; }
        public bool CheckM2AsynchCurrentS { get; set; }
        public bool CheckM2AsynchVoltageS { get; set; }
        public bool CheckM2AsynchPS { get; set; }
        public bool CheckM2AsynchIS { get; set; }
        public bool CheckM2AsynchDS { get; set; }
        public bool CheckM2Asynchx1S { get; set; }
        public bool CheckM2Asynchx2S { get; set; }
        public bool CheckM2Asynchx3S { get; set; }
        public string AddrM2AsynchSpeedR { get; set; }
        public string AddrM2AsynchPositionR { get; set; }
        public string AddrM2AsynchTorqueR { get; set; }
        public string AddrM2AsynchCurrentR { get; set; }
        public string AddrM2AsynchVoltageR { get; set; }
        public string AddrM2AsynchPR { get; set; }
        public string AddrM2AsynchIR { get; set; }
        public string AddrM2AsynchDR { get; set; }
        public string AddrM2Asynchx1R { get; set; }
        public string AddrM2Asynchx2R { get; set; }
        public string AddrM2Asynchx3R { get; set; }
        public bool CheckM2AsynchSpeedR { get; set; }
        public bool CheckM2AsynchPositionR { get; set; }
        public bool CheckM2AsynchTorqueR { get; set; }
        public bool CheckM2AsynchCurrentR { get; set; }
        public bool CheckM2AsynchVoltageR { get; set; }
        public bool CheckM2AsynchPR { get; set; }
        public bool CheckM2AsynchIR { get; set; }
        public bool CheckM2AsynchDR { get; set; }
        public bool CheckM2Asynchx1R { get; set; }
        public bool CheckM2Asynchx2R { get; set; }
        public bool CheckM2Asynchx3R { get; set; }
        public string AddrM2BLDCSpeedS { get; set; }
        public string AddrM2BLDCPositionS { get; set; }
        public string AddrM2BLDCTorqueS { get; set; }
        public string AddrM2BLDCCurrentS { get; set; }
        public string AddrM2BLDCVoltageS { get; set; }
        public string AddrM2BLDCPS { get; set; }
        public string AddrM2BLDCIS { get; set; }
        public string AddrM2BLDCDS { get; set; }
        public string AddrM2BLDCx1S { get; set; }
        public string AddrM2BLDCx2S { get; set; }
        public string AddrM2BLDCx3S { get; set; }
        public bool CheckM2BLDCSpeedS { get; set; }
        public bool CheckM2BLDCPositionS { get; set; }
        public bool CheckM2BLDCTorqueS { get; set; }
        public bool CheckM2BLDCCurrentS { get; set; }
        public bool CheckM2BLDCVoltageS { get; set; }
        public bool CheckM2BLDCPS { get; set; }
        public bool CheckM2BLDCIS { get; set; }
        public bool CheckM2BLDCDS { get; set; }
        public bool CheckM2BLDCx1S { get; set; }
        public bool CheckM2BLDCx2S { get; set; }
        public bool CheckM2BLDCx3S { get; set; }
        public string AddrM2BLDCSpeedR { get; set; }
        public string AddrM2BLDCPositionR { get; set; }
        public string AddrM2BLDCTorqueR { get; set; }
        public string AddrM2BLDCCurrentR { get; set; }
        public string AddrM2BLDCVoltageR { get; set; }
        public string AddrM2BLDCPR { get; set; }
        public string AddrM2BLDCIR { get; set; }
        public string AddrM2BLDCDR { get; set; }
        public string AddrM2BLDCx1R { get; set; }
        public string AddrM2BLDCx2R { get; set; }
        public string AddrM2BLDCx3R { get; set; }
        public bool CheckM2BLDCSpeedR { get; set; }
        public bool CheckM2BLDCPositionR { get; set; }
        public bool CheckM2BLDCTorqueR { get; set; }
        public bool CheckM2BLDCCurrentR { get; set; }
        public bool CheckM2BLDCVoltageR { get; set; }
        public bool CheckM2BLDCPR { get; set; }
        public bool CheckM2BLDCIR { get; set; }
        public bool CheckM2BLDCDR { get; set; }
        public bool CheckM2BLDCx1R { get; set; }
        public bool CheckM2BLDCx2R { get; set; }
        public bool CheckM2BLDCx3R { get; set; }
        public string AddrM2PMSMSpeedS { get; set; }
        public string AddrM2PMSMPositionS { get; set; }
        public string AddrM2PMSMTorqueS { get; set; }
        public string AddrM2PMSMCurrentS { get; set; }
        public string AddrM2PMSMVoltageS { get; set; }
        public string AddrM2PMSMPS { get; set; }
        public string AddrM2PMSMIS { get; set; }
        public string AddrM2PMSMDS { get; set; }
        public string AddrM2PMSMx1S { get; set; }
        public string AddrM2PMSMx2S { get; set; }
        public string AddrM2PMSMx3S { get; set; }
        public bool CheckM2PMSMSpeedS { get; set; }
        public bool CheckM2PMSMPositionS { get; set; }
        public bool CheckM2PMSMTorqueS { get; set; }
        public bool CheckM2PMSMCurrentS { get; set; }
        public bool CheckM2PMSMVoltageS { get; set; }
        public bool CheckM2PMSMPS { get; set; }
        public bool CheckM2PMSMIS { get; set; }
        public bool CheckM2PMSMDS { get; set; }
        public bool CheckM2PMSMx1S { get; set; }
        public bool CheckM2PMSMx2S { get; set; }
        public bool CheckM2PMSMx3S { get; set; }
        public string AddrM2PMSMSpeedR { get; set; }
        public string AddrM2PMSMPositionR { get; set; }
        public string AddrM2PMSMTorqueR { get; set; }
        public string AddrM2PMSMCurrentR { get; set; }
        public string AddrM2PMSMVoltageR { get; set; }
        public string AddrM2PMSMPR { get; set; }
        public string AddrM2PMSMIR { get; set; }
        public string AddrM2PMSMDR { get; set; }
        public string AddrM2PMSMx1R { get; set; }
        public string AddrM2PMSMx2R { get; set; }
        public string AddrM2PMSMx3R { get; set; }
        public bool CheckM2PMSMSpeedR { get; set; }
        public bool CheckM2PMSMPositionR { get; set; }
        public bool CheckM2PMSMTorqueR { get; set; }
        public bool CheckM2PMSMCurrentR { get; set; }
        public bool CheckM2PMSMVoltageR { get; set; }
        public bool CheckM2PMSMPR { get; set; }
        public bool CheckM2PMSMIR { get; set; }
        public bool CheckM2PMSMDR { get; set; }
        public bool CheckM2PMSMx1R { get; set; }
        public bool CheckM2PMSMx2R { get; set; }
        public bool CheckM2PMSMx3R { get; set; }
        public string AddrM1SpeedSNOP { get; set; }
        public string AddrM1PositionSNOP { get; set; }
        public string AddrM1TorqueSNOP { get; set; }
        public string AddrM1CurrentSNOP { get; set; }
        public string AddrM1VoltageSNOP { get; set; }
        public string AddrM1PSNOP { get; set; }
        public string AddrM1ISNOP { get; set; }
        public string AddrM1DSNOP { get; set; }
        public string AddrM1x1SNOP { get; set; }
        public string AddrM1x2SNOP { get; set; }
        public string AddrM1x3SNOP { get; set; }
        public string AddrM1SpeedRNOP { get; set; }
        public string AddrM1PositionRNOP { get; set; }
        public string AddrM1TorqueRNOP { get; set; }
        public string AddrM1PowerRNOP { get; set; }
        public string AddrM1CurrentRNOP { get; set; }
        public string AddrM1VoltageRNOP { get; set; }
        public string AddrM1PRNOP { get; set; }
        public string AddrM1IRNOP { get; set; }
        public string AddrM1DRNOP { get; set; }
        public string AddrM1x1RNOP { get; set; }
        public string AddrM1x2RNOP { get; set; }
        public string AddrM1x3RNOP { get; set; }
        public string AddrM2DCSpeedSNOP { get; set; }
        public string AddrM2DCPositionSNOP { get; set; }
        public string AddrM2DCTorqueSNOP { get; set; }
        public string AddrM2DCCurrentSNOP { get; set; }
        public string AddrM2DCVoltageSNOP { get; set; }
        public string AddrM2DCPSNOP { get; set; }
        public string AddrM2DCISNOP { get; set; }
        public string AddrM2DCDSNOP { get; set; }
        public string AddrM2DCx1SNOP { get; set; }
        public string AddrM2DCx2SNOP { get; set; }
        public string AddrM2DCx3SNOP { get; set; }
        public string AddrM2DCSpeedRNOP { get; set; }
        public string AddrM2DCPositionRNOP { get; set; }
        public string AddrM2DCTorqueRNOP { get; set; }
        public string AddrM2DCPowerRNOP { get; set; }
        public string AddrM2DCCurrentRNOP { get; set; }
        public string AddrM2DCVoltageRNOP { get; set; }
        public string AddrM2DCPRNOP { get; set; }
        public string AddrM2DCIRNOP { get; set; }
        public string AddrM2DCDRNOP { get; set; }
        public string AddrM2DCx1RNOP { get; set; }
        public string AddrM2DCx2RNOP { get; set; }
        public string AddrM2DCx3RNOP { get; set; }
        public string AddrM2AsynchSpeedSNOP { get; set; }
        public string AddrM2AsynchPositionSNOP { get; set; }
        public string AddrM2AsynchTorqueSNOP { get; set; }
        public string AddrM2AsynchCurrentSNOP { get; set; }
        public string AddrM2AsynchVoltageSNOP { get; set; }
        public string AddrM2AsynchPSNOP { get; set; }
        public string AddrM2AsynchISNOP { get; set; }
        public string AddrM2AsynchDSNOP { get; set; }
        public string AddrM2Asynchx1SNOP { get; set; }
        public string AddrM2Asynchx2SNOP { get; set; }
        public string AddrM2Asynchx3SNOP { get; set; }
        public string AddrM2AsynchSpeedRNOP { get; set; }
        public string AddrM2AsynchPositionRNOP { get; set; }
        public string AddrM2AsynchTorqueRNOP { get; set; }
        public string AddrM2AsynchPowerRNOP { get; set; }
        public string AddrM2AsynchCurrentRNOP { get; set; }
        public string AddrM2AsynchVoltageRNOP { get; set; }
        public string AddrM2AsynchPRNOP { get; set; }
        public string AddrM2AsynchIRNOP { get; set; }
        public string AddrM2AsynchDRNOP { get; set; }
        public string AddrM2Asynchx1RNOP { get; set; }
        public string AddrM2Asynchx2RNOP { get; set; }
        public string AddrM2Asynchx3RNOP { get; set; }
        public string AddrM2BLDCSpeedSNOP { get; set; }
        public string AddrM2BLDCPositionSNOP { get; set; }
        public string AddrM2BLDCTorqueSNOP { get; set; }
        public string AddrM2BLDCCurrentSNOP { get; set; }
        public string AddrM2BLDCVoltageSNOP { get; set; }
        public string AddrM2BLDCPSNOP { get; set; }
        public string AddrM2BLDCISNOP { get; set; }
        public string AddrM2BLDCDSNOP { get; set; }
        public string AddrM2BLDCx1SNOP { get; set; }
        public string AddrM2BLDCx2SNOP { get; set; }
        public string AddrM2BLDCx3SNOP { get; set; }
        public string AddrM2BLDCSpeedRNOP { get; set; }
        public string AddrM2BLDCPositionRNOP { get; set; }
        public string AddrM2BLDCTorqueRNOP { get; set; }
        public string AddrM2BLDCPowerRNOP { get; set; }
        public string AddrM2BLDCCurrentRNOP { get; set; }
        public string AddrM2BLDCVoltageRNOP { get; set; }
        public string AddrM2BLDCPRNOP { get; set; }
        public string AddrM2BLDCIRNOP { get; set; }
        public string AddrM2BLDCDRNOP { get; set; }
        public string AddrM2BLDCx1RNOP { get; set; }
        public string AddrM2BLDCx2RNOP { get; set; }
        public string AddrM2BLDCx3RNOP { get; set; }
        public string AddrM2PMSMSpeedSNOP { get; set; }
        public string AddrM2PMSMPositionSNOP { get; set; }
        public string AddrM2PMSMTorqueSNOP { get; set; }
        public string AddrM2PMSMCurrentSNOP { get; set; }
        public string AddrM2PMSMVoltageSNOP { get; set; }
        public string AddrM2PMSMPSNOP { get; set; }
        public string AddrM2PMSMISNOP { get; set; }
        public string AddrM2PMSMDSNOP { get; set; }
        public string AddrM2PMSMx1SNOP { get; set; }
        public string AddrM2PMSMx2SNOP { get; set; }
        public string AddrM2PMSMx3SNOP { get; set; }
        public string AddrM2PMSMSpeedRNOP { get; set; }
        public string AddrM2PMSMPositionRNOP { get; set; }
        public string AddrM2PMSMTorqueRNOP { get; set; }
        public string AddrM2PMSMPowerRNOP { get; set; }
        public string AddrM2PMSMCurrentRNOP { get; set; }
        public string AddrM2PMSMVoltageRNOP { get; set; }
        public string AddrM2PMSMPRNOP { get; set; }
        public string AddrM2PMSMIRNOP { get; set; }
        public string AddrM2PMSMDRNOP { get; set; }
        public string AddrM2PMSMx1RNOP { get; set; }
        public string AddrM2PMSMx2RNOP { get; set; }
        public string AddrM2PMSMx3RNOP { get; set; }
        public string ReadGenAddr { get; set; }
        public string ReadGenNOP { get; set; }
        public string WriteGenAddr { get; set; }
        public string WriteGenNOP { get; set; }
    }
}